spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    generate-ddl : false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          trace

# JWT
jwt:
  secret: YOUR_SECRET_KEY
  access-expired: 1800 # 30(분) - 단위 (초)